name: Trigger auto deployment for newcontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/newcontainer-AutoDeployTrigger-3931ceb3-0bc0-49c0-aa16-b64f9b0868f7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NEWCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEWCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEWCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrsnreg.azurecr.io
          registryUsername: ${{ secrets.NEWCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEWCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: newcontainer
          resourceGroup: Snambissan
          imageToBuild: acrsnreg.azurecr.io/newcontainer:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


